const products = [
  {
    title: "Magnetite",
    category: 'Rock',
    price: 89.0,
    img: "../assets/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 'MPB',
    price: 69.0,
    img: "../assets/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 'Rock',
    price: 49.0,
    img: "../assets/3.jpg",
    band: "Nirvana",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 'Rock',
    price: 49.0,
    img: "../assets/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "A Tábua de Esmeralda",
    category: 'MPB',
    price: 49.0,
    img: "../assets/5.jpg",
    band: "Jorge Ben Jor",
    year: 1974,
    id: 4,
  },
  {
    title: "Refazenda",
    category: 'MPB',
    price: 69.0,
    img: "../assets/6.jpg",
    band: "Gilberto Gil",
    year: 1975,
    id: 5,
  },
  {
    title: "Bloco do Eu Sozinho",
    category: 'MPB',
    price: 59.0,
    img: "../assets/7.jpg",
    band: "Los Hermanos",
    year: 2001,
    id: 6,
  },
  {
    title: "50 Anos de Chão",
    category: 'Forro',
    price: 79.0,
    img: "../assets/8.jpg",
    band: "Luiz Gonzaga",
    year: 1996,
    id: 7,
  },
  {
    title: "Diferente dos Iguais",
    category: 'Forró',
    price: 89.0,
    img: "../assets/9.jpg",
    band: "Tarcísio do Acordeon",
    year: 2019,
    id: 8,
  },
  {
    title: "Portela passado de glória",
    category: 'Samba',
    price: 99.0,
    img: "../assets/10.jpg",
    band: "Velha Guarda da Portela",
    year: 1970,
    id: 9,
  },
  {
    title: "Illmatic",
    category: 'Hip-Hop',
    price: 49.0,
    img: "../assets/11.jpg",
    band: "Nas",
    year: 1994,
    id: 10,
  },
  {
    title: "Sobrevivendo no inferno",
    category: 'Rap',
    price: 39.0,
    img: "../assets/12.jpg",
    band: "Racionais MC's",
    year: 1970,
    id: 11,
  },
  {
    title: "Two Sevens Clash",
    category: 'Reggae',
    price: 79.0,
    img: "../assets/13.jpg",
    band: "Culture",
    year: 1977,
    id: 12,
  },
  {
    title: "Love Me Back",
    category: 'Pop',
    price: 59.0,
    img: "../assets/14.jpg",
    band: "Jazmine Sullivan",
    year: 2010,
    id: 13,
  },
  {
    title: "Folklore",
    category: 'Pop',
    price: 69.0,
    img: "../assets/15.jpg",
    band: "Taylor Swift",
    year: 2020,
    id: 14,
  },
  {
    title: "Melodrama",
    category: 'Pop',
    price: 119.0,
    img: "../assets/16.jpg",
    band: "Lorde",
    year: 2017,
    id: 15,
  },
  {
    title: "Daddy's Home",
    category: 'Pop',
    price: 69.0,
    img: "../assets/17.png",
    band: "St. Vincent",
    year: 2021,
    id: 16,
  },
  {
    title: "São João Na Roça",
    category: 'Forró',
    price: 99.0,
    img: "../assets/19.jpg",
    band: "Luiz Gonzaga",
    year: 1957,
    id: 17,
  },
  {
    title: "Utopia",
    category: 'Rap',
    price: 49.0,
    img: "../assets/21.jpg",
    band: "Dj Jamaika",
    year: 1998,
    id: 18,
  },
  {
    title: "Bem-vindos ao Inferno",
    category: 'Rap',
    price: 39.0,
    img: "../assets/24.jpg",
    band: "Sistema Negro",
    year: 1994,
    id: 19,
  },
  {
    title: "Arrependa-se",
    category: 'Rap',
    price: 9.0,
    img: "../assets/22.jpg",
    band: "Apocalipse 16",
    year: 1998,
    id: 20,
  },
  {
    title: "Eu Tiro é Onda",
    category: 'Rap',
    price: 39.0,
    img: "../assets/23.jpg",
    band: "Marcelo D2",
    year: 1998,
    id: 21,
  },
  {
    title: "The Infamous",
    category: 'Hip-Hop',
    price: 59.0,
    img: "../assets/25.jpg",
    band: "Mobb Deep",
    year: 1995,
    id: 22,
  },
  {
    title: "The Chronic",
    category: 'Hip-Hop',
    price: 19.0,
    img: "../assets/26.jpg",
    band: "Dr. Dre",
    year: 1992,
    id: 23,
  },
  {
    title: "Damn",
    category: 'Hip-Hop',
    price: 19.0,
    img: "../assets/27.jpg",
    band: "Kendrick Lamar",
    year: 2017,
    id: 24,
  },
  {
    title: "Starting Over",
    category: 'Country',
    price: 69.0,
    img: "../assets/28.jpg",
    band: "Chris Stapleton",
    year: 2020,
    id: 25,
  },
  {
    title: "Gospel Collection Vol. 07",
    category: 'Gospel',
    price: 9.0,
    img: "../assets/29.jpg",
    band: "Nueva Expression",
    year: 2008,
    id: 26,
  },
  {
    title: "Sem Palavras",
    category: 'Gospel',
    price: 9.0,
    img: "../assets/30.jpg",
    band: "Cassiane",
    year: 1996,
    id: 27,
  },
  {
    title: "Thank U, Next",
    category: 'Pop',
    price: 19.0,
    img: "../assets/31.jpg",
    band: "Ariana Grande",
    year: 2019,
    id: 28,
  }
];

